//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL3M
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsInfo()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int GoodsId { get; set; }
        public string GoodsName { get; set; }
        public string GoodsModel { get; set; }
        public string GoodsDes { get; set; }
        public string Unit { get; set; }
        public Nullable<double> InUnitPrice { get; set; }
        public Nullable<double> OutUnitPrice { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
