//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL3M
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceFileAttaches = new HashSet<InvoiceFileAttach>();
        }
    
        public int InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CusId { get; set; }
        public string TypePay { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual InvoiceDetail InvoiceDetail { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceFileAttach> InvoiceFileAttaches { get; set; }
    }
}
