//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL3M
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDetail
    {
        public int StoreDetailsId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual StoreInfo StoreInfo { get; set; }
    }
}
